Feature/twcookie 28 import export settings/twcookie 33 handover issues
towa-digital/towa-gdpr-plugin pull request #12
Opened 2020-04-07 14:39 UTC by Martin-Welte

## TLDR; 

* only send data from the plugin to the frontend

## What to test & how to test 

* if other acf options are present, they are not included anymore

## solves Issues
* prevents potential data leak

2020-04-07 19:10 UTC, SahinU88 requested changes
@Martin-Welte 
- please apply php-cs-fixer

2020-04-07 19:18 UTC, szepeviktor commented
@Martin-Welte Done in #13

2020-04-07 19:31 UTC, SahinU88 commented
@Martin-Welte 
- can you give a brief description what should be tested here and how I can verify it?

2020-04-08 09:23 UTC, Martin-Welte commented
@SahinU88  i updated the PR description with aditional information

2020-04-08 13:39 UTC, SahinU88 approved these changes

2020-04-08 14:04 UTC, szepeviktor commented
Maybe CS is missing here,
done in #13

2020-04-08 16:40 UTC, Martin-Welte commented
> Maybe CS is missing here,
> done in #13

what do you mean?

2020-04-08 16:56 UTC, szepeviktor commented
There is a code styling issue in this PR and #13 would resolve it.

2020-04-09 07:18 UTC, merged